#!/usr/bin/env bash
# Stand up the control plane in one command. Generates the two secrets on first
# run, records them in ./.env, builds the image, and starts the stack detached.
#
# The secrets live in .env rather than only in this shell because Compose reads
# it automatically: `docker compose down`, `logs`, and `restart` all need the
# same values, and a second terminal has none of them. It also keeps
# EJENIX_DELIVERY_SEED stable across restarts, which is the whole point of the
# seed — devices verify server-signed deltas against the key derived from it.
set -euo pipefail

cd "$(dirname "$0")"

env_file=".env"

gen_hex32() { head -c 32 /dev/urandom | od -An -tx1 | tr -d ' \n'; }

# Read a key back out of .env, so a re-run reuses what it generated before.
from_env_file() {
  [[ -f "$env_file" ]] || return 0
  sed -n "s/^$1=//p" "$env_file" | tail -1
}

: "${EJENIX_ADMIN_KEY:=$(from_env_file EJENIX_ADMIN_KEY)}"
: "${EJENIX_DELIVERY_SEED:=$(from_env_file EJENIX_DELIVERY_SEED)}"

generated=0
if [[ -z "$EJENIX_ADMIN_KEY" ]]; then
  EJENIX_ADMIN_KEY="$(gen_hex32)"
  generated=1
fi
if [[ -z "$EJENIX_DELIVERY_SEED" ]]; then
  EJENIX_DELIVERY_SEED="$(gen_hex32)"
  generated=1
fi
export EJENIX_ADMIN_KEY EJENIX_DELIVERY_SEED

# 0600: this file holds the admin token and the delivery seed.
umask 077
cat >"$env_file" <<EOF
# Generated by up.sh — gitignored. Keep these: the admin key authenticates
# administration, and the delivery seed must stay stable or devices stop
# trusting server-signed deltas.
EJENIX_ADMIN_KEY=$EJENIX_ADMIN_KEY
EJENIX_DELIVERY_SEED=$EJENIX_DELIVERY_SEED
EJENIX_PORT=${EJENIX_PORT:-8080}
EOF

if ((generated)); then
  echo "Generated secrets, saved to deploy/docker/.env:"
  echo "  EJENIX_ADMIN_KEY=$EJENIX_ADMIN_KEY"
  echo "  EJENIX_DELIVERY_SEED=$EJENIX_DELIVERY_SEED"
  echo "Save the admin key — you need it to administer apps."
  echo
fi

compose() {
  if docker compose version >/dev/null 2>&1; then
    docker compose "$@"
  else
    docker-compose "$@"
  fi
}

compose up --build -d

echo
echo "Control plane:  http://localhost:${EJENIX_PORT:-8080}"
echo "Health:         curl http://localhost:${EJENIX_PORT:-8080}/v1/health"
echo "Logs:           (cd deploy/docker && docker compose logs -f)"
echo "Tear down:      (cd deploy/docker && docker compose down)   # add -v to wipe data"
