// GENERATED BY `ejenix gen` — do not edit by hand.
// Regenerate with `ejenix gen` after changing @Patchable code.
library;

import 'package:ejenix_flutter/ejenix_flutter.dart';

import 'app_state.dart';
import 'design_system.dart';

/// Grants a patch exactly the capabilities marked @Patchable.
/// Pass the result to `EjenixPatchView(extend: ...)`.
HostExtension appCapabilities(TodoRepository todoRepository) {
  return (registry, ctx) {
    registry
      ..registerGlobal('PrimaryButton', (_, a) {
        final m = ctx.args(a);
        return PrimaryButton(
          label: m['label'] as String? ?? '',
          onPressed: ctx.callback(m['onPressed']),
        );
      })
      ..registerGlobal('StatCard', (_, a) {
        final m = ctx.args(a);
        return StatCard(
          label: m['label'] as String? ?? '',
          value: m['value'] as String? ?? '',
        );
      })
      ..registerGlobal('App.todos', (_, __) => todoRepository.todosForPatch)
      ..registerGlobal(
        'App.pendingCount',
        (_, __) => todoRepository.pendingCount,
      )
      ..registerGlobal('App.addTodo', (_, a) {
        final m = ctx.args(a);
        todoRepository.add(m['title'] as String? ?? '');
        return null;
      })
      ..registerGlobal('App.toggleTodo', (_, a) {
        final m = ctx.args(a);
        todoRepository.toggle(m['id'] as int? ?? 0);
        return null;
      })
      ..registerGlobal('App.refresh', (_, __) async {
        await todoRepository.refresh();
        ctx.requestRebuild?.call();
        return null;
      });
  };
}
