// Copyright (c) Ejenix authors. MIT license.

/// A Flutter app architected to be **patchable**.
///
/// The shipped binary owns everything that matters: the route table, the design
/// system, the state, the network, and the signing key it trusts. One screen —
/// the home screen — is rendered from an interpreted patch, so its layout and
/// logic can be replaced over the air in minutes rather than a release cycle.
///
/// The load path here is the real one, minus the fetch: decode a signed bundle,
/// **verify it against a trusted key**, and only then run it. In production
/// `package:ejenix_loader` performs the fetch/stage/rollback lifecycle around
/// exactly these steps; a bundle that fails verification is never executed.
library;

import 'dart:typed_data';

import 'package:flutter/foundation.dart' show ValueListenable;
import 'package:flutter/material.dart';
import 'package:flutter/services.dart' show rootBundle;
import 'package:ejenix_bundle/bundle.dart';
import 'package:ejenix_flutter/ejenix_flutter.dart';

import 'app_capabilities.g.dart';
import 'app_state.dart';
import 'patch_channel.dart';

/// The public key this build trusts. Only patches signed by the matching private
/// key will ever run. Generated by `build.sh` (`ejenix keygen`).
const trustedPublicKeyHex = String.fromEnvironment('PATCH_PUBKEY');

/// A live `ejenix watch` server, e.g. `--dart-define=PATCH_URL=http://192.168.1.10:8787`.
///
/// Empty in a normal build: the app then runs only the patch that shipped in the
/// binary. This is a *development* convenience — production fetches from the
/// signed control plane via `package:ejenix_loader`. Either way the bytes are
/// verified before they run, so pointing this at a hostile server gains an
/// attacker nothing.
const patchServerUrl = String.fromEnvironment('PATCH_URL');

void main() => runApp(const PatchableApp());

class PatchableApp extends StatelessWidget {
  const PatchableApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Patchable App',
      theme: ThemeData(colorSchemeSeed: Colors.indigo, useMaterial3: true),
      // The app owns its route table. A patch may only navigate to routes
      // declared here — it cannot invent a destination.
      routes: {'/about': (_) => const AboutScreen()},
      home: const HomeScreen(),
    );
  }
}

/// Hosts the interpreted home screen.
class HomeScreen extends StatefulWidget {
  const HomeScreen({super.key});

  @override
  State<HomeScreen> createState() => _HomeScreenState();
}

class _HomeScreenState extends State<HomeScreen> {
  /// The app's state lives here, in the binary — not in the patch.
  final TodoRepository _repo = TodoRepository();

  /// The patch that shipped in the binary, plus any the dev server pushes. Both
  /// are verified against [trustedPublicKeyHex] before they can run.
  late final PatchChannel _channel = PatchChannel(
    assetPath: 'assets/home_screen.bundle',
    trustedPublicKeyHex: trustedPublicKeyHex,
    devServerUrl: patchServerUrl,
  )..start();

  @override
  void dispose() {
    _channel.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return StreamBuilder<VerifiedPatch>(
      stream: _channel.patches,
      builder: (context, snapshot) {
        if (snapshot.hasError) {
          // A patch that fails to verify is never executed. The app keeps
          // working — it just falls back to what shipped in the binary.
          return FallbackHomeScreen(reason: '${snapshot.error}');
        }
        if (!snapshot.hasData) {
          return const Scaffold(
            body: Center(child: CircularProgressIndicator()),
          );
        }
        final patch = snapshot.requireData;

        return Stack(
          children: [
            // A newly pushed module rebuilds the interpreter (InterpretedView's
            // didUpdateWidget), so the screen becomes the new patch without the
            // app restarting. That is what "push" means here.
            InterpretedView(
              module: patch.module,
              // Everything the patch may reach beyond stock Flutter.
              extend: appCapabilities(_repo),
              // A verified patch can still be unrunnable here — most often it
              // calls a capability added to the app after this build shipped,
              // since a patch cannot bring one with it. Route that to the same
              // native screen a missing patch uses, so the user never sees an
              // error widget where their app should be.
              errorBuilder: (context, error) =>
                  FallbackHomeScreen(reason: '$error'),
            ),
            // Says out loud whether you are looking at the patch that shipped in
            // the binary or one pushed over the air — otherwise "it changed!" is
            // impossible to distinguish from "I rebuilt the app".
            _PatchBadge(origin: patch.origin, status: _channel.status),
          ],
        );
      },
    );
  }
}

/// A small overlay reporting the patch's origin and the dev-server connection.
class _PatchBadge extends StatelessWidget {
  const _PatchBadge({required this.origin, required this.status});

  final PatchOrigin origin;
  final ValueListenable<String> status;

  @override
  Widget build(BuildContext context) {
    final pushed = origin == PatchOrigin.pushed;
    return SafeArea(
      child: Align(
        alignment: Alignment.bottomCenter,
        child: Padding(
          padding: const EdgeInsets.all(8),
          child: ValueListenableBuilder<String>(
            valueListenable: status,
            builder: (context, message, _) => Material(
              color: pushed ? Colors.green.shade700 : Colors.blueGrey.shade800,
              borderRadius: BorderRadius.circular(10),
              child: Padding(
                padding: const EdgeInsets.symmetric(
                  horizontal: 12,
                  vertical: 8,
                ),
                child: Column(
                  mainAxisSize: MainAxisSize.min,
                  children: [
                    Text(
                      pushed
                          ? 'PUSHED PATCH — over the air'
                          : 'BUNDLED PATCH — shipped in the binary',
                      style: const TextStyle(
                        color: Colors.white,
                        fontWeight: FontWeight.bold,
                        fontSize: 12,
                      ),
                    ),
                    const SizedBox(height: 2),
                    Text(
                      message,
                      textAlign: TextAlign.center,
                      style: const TextStyle(
                        color: Colors.white70,
                        fontSize: 10,
                      ),
                    ),
                  ],
                ),
              ),
            ),
          ),
        ),
      ),
    );
  }
}

/// Decodes a signed patch bundle and verifies it against [trustedPublicKeyHex]
/// before returning anything runnable. Throws if the bundle is malformed,
/// unsigned, tampered with, or signed by a key this build does not trust.
///
/// Verification happens **before** the bytes are ever interpreted: an attacker
/// who compromises the update server still cannot run code on a device, because
/// they cannot forge a signature from the key the binary trusts.
Module verifyPatch(Uint8List bytes, {required String trustedPublicKeyHex}) {
  final bundle = Bundle.decode(bytes);
  final result = bundle.verify(
    anchors: TrustAnchors.single(_unhex(trustedPublicKeyHex)),
  );
  if (!result.isValid) {
    throw StateError('patch rejected: ${result.failure}');
  }

  final (module, _) = bundle.decodeBody();
  return module;
}

/// Loads the patch shipped as an asset, then [verifyPatch]es it. In production
/// the bytes come from `package:ejenix_loader` instead — same verification.
Future<Module> loadVerifiedPatch(
  String assetPath, {
  required String trustedPublicKeyHex,
}) async {
  final data = await rootBundle.load(assetPath);
  return verifyPatch(
    data.buffer.asUint8List(),
    trustedPublicKeyHex: trustedPublicKeyHex,
  );
}

Uint8List _unhex(String hex) {
  final h = hex.trim();
  return Uint8List.fromList([
    for (var i = 0; i + 1 < h.length; i += 2)
      int.parse(h.substring(i, i + 2), radix: 16),
  ]);
}

/// What users see if no valid patch is available. An over-the-air patch system must always
/// have this: the binary alone is a working app.
class FallbackHomeScreen extends StatelessWidget {
  const FallbackHomeScreen({super.key, required this.reason});

  final String reason;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Todos')),
      body: Center(
        child: Padding(
          padding: const EdgeInsets.all(24),
          child: Column(
            mainAxisSize: MainAxisSize.min,
            children: [
              const Icon(Icons.info_outline, size: 40),
              const SizedBox(height: 12),
              const Text('Running the built-in screen.'),
              const SizedBox(height: 4),
              Text(
                reason,
                textAlign: TextAlign.center,
                style: Theme.of(context).textTheme.bodySmall,
              ),
            ],
          ),
        ),
      ),
    );
  }
}

class AboutScreen extends StatelessWidget {
  const AboutScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('About')),
      body: const Center(child: Text('A route the app owns.')),
    );
  }
}
