// Copyright (c) Ejenix authors. MIT license.

/// Regenerates `packages/server/lib/src/brand.dart` from the assets in
/// `docs/brand/`, so the control plane serves its own branding without an asset
/// directory to mount or a CDN to reach.
///
/// The dashboard is one self-contained page served from a `scratch` image:
/// there is nowhere to put a file, and a deployment may be air-gapped. Inlining
/// the bytes keeps the logo and the typefaces with the binary that serves them,
/// and keeps the page free of third-party requests.
///
///   dart run tool/embed_brand.dart            # after replacing an asset
///   dart run tool/embed_brand.dart --check    # CI: fail if out of date
library;

import 'dart:convert';
import 'dart:io';

/// Asset file -> the Dart identifier that will hold its bytes.
const _assets = <String, String>{
  'docs/brand/ejenix-logo.png': 'brandLogoPng',
  'docs/brand/inter.woff2': 'brandInterWoff2',
  'docs/brand/jetbrains-mono.woff2': 'brandJetBrainsMonoWoff2',
};

const _output = 'packages/server/lib/src/brand.dart';

void main(List<String> args) {
  final check = args.contains('--check');

  final encoded = <String, String>{};
  for (final path in _assets.keys) {
    final f = File(path);
    if (!f.existsSync()) {
      stderr.writeln('missing $path — run from the repository root.');
      exit(66);
    }
    encoded[path] = base64Encode(f.readAsBytesSync());
  }

  final generated = _render(encoded);
  final out = File(_output);
  final current = out.existsSync() ? out.readAsStringSync() : '';

  if (check) {
    if (current == generated) {
      stdout.writeln('brand.dart is up to date with docs/brand/');
      return;
    }
    stderr.writeln(
      '$_output is stale.\nRegenerate it: dart run tool/embed_brand.dart',
    );
    exit(1);
  }

  if (current == generated) {
    stdout.writeln('brand.dart already matches docs/brand/ — nothing to do.');
    return;
  }
  out.writeAsStringSync(generated);
  final total = encoded.values.fold<int>(0, (n, s) => n + s.length);
  stdout.writeln(
    'wrote $_output (${_assets.length} assets, $total base64 chars)',
  );
}

String _render(Map<String, String> encoded) {
  final b = StringBuffer()
    ..writeln('// Copyright (c) Ejenix authors. MIT license.')
    ..writeln('//')
    ..writeln('// GENERATED by tool/embed_brand.dart — do not edit by hand.')
    ..writeln(
      '// Source assets live in docs/brand/; regenerate after changing one.',
    )
    ..writeln()
    ..writeln("import 'dart:convert';")
    ..writeln("import 'dart:typed_data';")
    ..writeln()
    ..writeln(
      '/// Ejenix brand assets, inlined so the control plane serves its own',
    )
    ..writeln(
      '/// branding: the dashboard is one self-contained page served from a',
    )
    ..writeln(
      '/// `scratch` image, with no asset directory to mount, no CDN to reach, and',
    )
    ..writeln('/// no third-party request from an operator\'s browser.');

  for (final entry in _assets.entries) {
    final path = entry.key, ident = entry.value;
    final b64 = encoded[path]!;
    final priv = '_${ident}Base64';
    b
      ..writeln()
      ..writeln('/// Base64 of `$path`.')
      ..writeln('const $priv =');
    for (var i = 0; i < b64.length; i += 76) {
      final end = i + 76 > b64.length ? b64.length : i + 76;
      final last = end == b64.length;
      b.writeln("    '${b64.substring(i, end)}'${last ? ';' : ''}");
    }
    // Emit the shape `dart format` would produce, so the generated file is
    // already clean and `--check` compares like with like.
    final oneLine = 'final Uint8List $ident = base64Decode($priv);';
    b
      ..writeln()
      ..writeln('/// Decoded bytes of `$path`.')
      ..writeln(
        oneLine.length <= 80
            ? oneLine
            : 'final Uint8List $ident = base64Decode(\n  $priv,\n);',
      );
  }
  return b.toString();
}
