#!/usr/bin/env bash
# Install the control plane on this machine as a systemd service.
#
#   sudo ./deploy.sh --target bare-metal
#   ./deploy.sh --target bare-metal --dry-run
#
# Unlike the managed targets there is no container here: the server is
# AOT-compiled to a single self-contained native executable and run directly.
# Storage is the local disk, so this target is durable by construction.
#
# The unit uses DynamicUser=yes and StateDirectory, so the service runs as a
# transient unprivileged user and systemd owns the data directory's permissions
# — no service account to create, and nothing running as root.
set -euo pipefail

# shellcheck source=deploy/cloud/_common.sh
source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/_common.sh"

PREFIX="/opt/ejenix"
SECRETS_DIR="/etc/ejenix"
UNIT_NAME="ejenix-control-plane"
STATE_DIR_NAME="ejenix"

usage() {
  cat <<EOF
Install the Ejenix control plane as a systemd service on this machine.

Usage: sudo ./deploy.sh --target bare-metal [options]

Options:
  --prefix <dir>       Install directory for the binary (default: $PREFIX)
  --secrets-dir <dir>  Directory for the env file (default: $SECRETS_DIR)
  --unit <name>        systemd unit name (default: $UNIT_NAME)
$(common_usage_flags)

Data lives in /var/lib/$STATE_DIR_NAME, created and owned by systemd.
EOF
}

while [[ $# -gt 0 ]]; do
  if common_arg "$@"; then
    shift "$CONSUMED"
    continue
  fi
  case "$1" in
    --prefix) PREFIX="${2:?--prefix needs a value}"; shift 2 ;;
    --prefix=*) PREFIX="${1#*=}"; shift ;;
    --secrets-dir) SECRETS_DIR="${2:?--secrets-dir needs a value}"; shift 2 ;;
    --secrets-dir=*) SECRETS_DIR="${1#*=}"; shift ;;
    --unit) UNIT_NAME="${2:?--unit needs a value}"; shift 2 ;;
    --unit=*) UNIT_NAME="${1#*=}"; shift ;;
    -h | --help) usage; exit 0 ;;
    *) die "unknown argument: $1 (try --help)" ;;
  esac
done

# ---------------------------------------------------------------- preflight --
step "Preflight"

need_cmd dart "Install: https://dart.dev/get-dart"

if ! ((DRY_RUN)); then
  command -v systemctl >/dev/null 2>&1 ||
    die "systemctl not found — this target installs a systemd service.

       On macOS or a non-systemd host, use the docker target instead:
         ./deploy.sh --target docker"
fi

# Everything below writes outside $HOME, so require root up front rather than
# failing halfway through the install.
SUDO=""
if [[ "${EUID:-$(id -u)}" -ne 0 ]]; then
  if command -v sudo >/dev/null 2>&1; then
    SUDO="sudo"
    ((DRY_RUN)) || note "not running as root — using sudo for install steps"
  elif ! ((DRY_RUN)); then
    die "must run as root (or have sudo available) to install a systemd unit.
       Retry as: sudo ./deploy.sh --target bare-metal"
  fi
fi

note "prefix:   $PREFIX"
note "secrets:  $SECRETS_DIR/secrets.env"
note "unit:     $UNIT_NAME.service"
note "data:     /var/lib/$STATE_DIR_NAME"

ensure_secrets
announce_dry_run

# ----------------------------------------------------------------- compile --
step "AOT-compiling the control plane"

run dart pub get --directory "$ROOT"
BINARY="$ROOT/build/ejenix_server"
run mkdir -p "$ROOT/build"
run dart compile exe "$ROOT/packages/server/bin/ejenix_server.dart" -o "$BINARY"

# ----------------------------------------------------------------- install --
step "Installing the binary"

run $SUDO install -d -m 0755 "$PREFIX"
run $SUDO install -m 0755 "$BINARY" "$PREFIX/ejenix_server"

step "Writing the environment file"

# 0600 and root-owned: it holds the admin token and the delivery seed. systemd
# reads it as root before dropping to the DynamicUser.
run $SUDO install -d -m 0700 "$SECRETS_DIR"
if ((DRY_RUN)); then
  note "(dry run) write $SECRETS_DIR/secrets.env (mode 0600) with EJENIX_ADMIN_KEY, EJENIX_DELIVERY_SEED"
else
  tmp_env="$(mktemp)"
  cat >"$tmp_env" <<EOF
# Ejenix control plane — generated by deploy/cloud/bare-metal.sh
# The seed must stay stable: devices verify server-signed deltas against the
# key derived from it.
EJENIX_ADMIN_KEY=$EJENIX_ADMIN_KEY
EJENIX_DELIVERY_SEED=$EJENIX_DELIVERY_SEED
EJENIX_PORT=$EJENIX_PORT
EOF
  $SUDO install -m 0600 "$tmp_env" "$SECRETS_DIR/secrets.env"
  rm -f "$tmp_env"
fi

step "Installing the systemd unit"

unit_body="$(
  cat <<EOF
[Unit]
Description=Ejenix control plane
Documentation=https://github.com/ejenix/opensource
After=network-online.target
Wants=network-online.target

[Service]
ExecStart=$PREFIX/ejenix_server
Environment=EJENIX_DATA_DIR=/var/lib/$STATE_DIR_NAME
EnvironmentFile=$SECRETS_DIR/secrets.env
Restart=always
RestartSec=2

# The service needs no privileges beyond its own state directory.
DynamicUser=yes
StateDirectory=$STATE_DIR_NAME
NoNewPrivileges=yes
PrivateTmp=yes
ProtectSystem=strict
ProtectHome=yes
ProtectKernelTunables=yes
ProtectControlGroups=yes
RestrictAddressFamilies=AF_INET AF_INET6 AF_UNIX
RestrictNamespaces=yes
LockPersonality=yes
MemoryDenyWriteExecute=no

[Install]
WantedBy=multi-user.target
EOF
)"

if ((DRY_RUN)); then
  note "(dry run) unit that would be written to /etc/systemd/system/$UNIT_NAME.service:"
  printf '%s\n' "$unit_body" | sed 's/^/     /'
else
  tmp_unit="$(mktemp)"
  printf '%s\n' "$unit_body" >"$tmp_unit"
  $SUDO install -m 0644 "$tmp_unit" "/etc/systemd/system/$UNIT_NAME.service"
  rm -f "$tmp_unit"
fi

step "Starting the service"

run $SUDO systemctl daemon-reload
run $SUDO systemctl enable --now "$UNIT_NAME"

URL=""
if ! ((DRY_RUN)); then
  # Give it a moment, then confirm it is actually serving rather than assuming.
  sleep 2
  if $SUDO systemctl is-active --quiet "$UNIT_NAME"; then
    URL="http://localhost:$EJENIX_PORT"
    note "unit is active"
  else
    die "the unit failed to start.
       Inspect it: journalctl -u $UNIT_NAME -n 50 --no-pager"
  fi
fi

report_ready "$URL"

if ! ((DRY_RUN)); then
  echo
  echo "Service management:"
  echo "  Logs:     journalctl -u $UNIT_NAME -f"
  echo "  Restart:  sudo systemctl restart $UNIT_NAME"
  echo "  Stop:     sudo systemctl disable --now $UNIT_NAME"
  echo
  echo "Front it with nginx or Caddy for TLS before exposing it publicly."
fi
