// GENERATED BY `ejenix gen` — do not edit by hand.
// Regenerate with `ejenix gen` after changing @Patchable code.
library;

import 'flutter.dart';

class PrimaryButton implements Widget {
  external PrimaryButton({required String label, void Function()? onPressed});
}

class StatCard implements Widget {
  external StatCard({required String label, required String value});
}

class App {
  external static List<Map<String, Object?>> get todos;
  external static int get pendingCount;
  external static void addTodo(String title);
  external static void toggleTodo(int id);
  external static Future<void> refresh();
}
